#! /bin/zsh

# generate theme from image
wal -i $@

# restart lemonbar
pkill lemonbar
lemonbar.sh &>/dev/null &

# # theme spotify
# oomoxify-cli ~/.cache/wal/colors-oomox
spicetify apply
#
# # generate css for discord and apply it
# ~/documents/gits/wal-discord/wal-discord
# beautifuldiscord --css ~/.cache/wal-discord/style.css
#
# # apply theme for steam
# wal_steam

