#!/bin/bash

current=$( i3-msg -t get_workspaces \
  | jq '.[] | select(.focused==true).name' \
  | cut -d"\"" -f2)

i3-msg "rename workspace $current to temporary; rename workspace $1 to $current; rename workspace temporary to $1"
